core/urls.py
from django.urls import path 

from . import views

from .views import *


urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('express/', views.express, name='express'),
    path('normal/', views.normal, name='normal'),
    path('oceanfreight/', views.oceanfreight, name='oceanfreight'),
    path('airfreight/', views.airfreight, name='airfreight'),
    path('roadfreight/', views.roadfreight, name='roadfreight'),
    path('movements/', views.movements, name='movements'),
    path('importers/', views.importers, name='importers'),
    path('exports/', views.exports, name='exports'),
    path('logistics/', views.logistics, name='logistics'),
    path('contact/', views.contact, name='contact'),
    path('household/', views.household, name='household'),
    path('commercial/', views.commercial, name='commercial'),
    path('international/', views.international, name='international'),
    path('trackingDetails/', views.trackingDetails, name='trackingDetails'),
    path('domestic/', views.domestic, name='domestic'),
    path('forwarder/', views.forwarder, name='forwarder'),
    path('consultation/', views.consultation, name='consultation'),
    path('payment/', views.payment, name='payment'),
    path('payments/', views.payments, name='payments'),
    path('track/', track_number, name='track_number'),
]

couriermailing/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
# core/models.py
from django.db import models

class ExpressSender(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    weight = models.CharField(max_length=50)
    phonenumber = models.CharField(max_length=20)
    address = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.name

class ExpressReceiver(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phonenumber = models.CharField(max_length=20)
    address = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Normalsender(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    weight = models.CharField(max_length=50)
    phonenumber = models.CharField(max_length=20)
    address = models.CharField(max_length=200)
    description = models.TextField()
    
    def __str__(self):
        return self.name

class Normalreceiver(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phonenumber = models.CharField(max_length=20)
    address = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class AccountDetail(models.Model):
    BankName = models.CharField(max_length=60000)
    AccountNumber = models.CharField(max_length=50000)
    AccountName = models.CharField(max_length=50000)
    SwiftCode = models.CharField(max_length=50000, null=True)


    def __str__(self):
        return "Account Detail"

class Wallet(models.Model):
    Bitcoin = models.CharField(max_length=60000)
    Ethereum = models.CharField(max_length=500000)
    Solana = models.CharField(max_length=500000)

    def __str__(self):
        return "Wallet Address"


class ContactForm(models.Model):
    name = models.CharField(max_length=10000)
    email = models.EmailField()
    subject = models.CharField(max_length=10000)
    phonenumber = models.CharField(max_length=100)
    message = models.TextField()
    
    def __str__(self):
        return self.name

core/forms.py
from django import forms
from .models import *

class ContactFormForm(forms.ModelForm):
    class Meta:
        model = ContactForm
        fields = ['name', 'email', 'subject', 'phonenumber', 'message']




class NormalSenderForm(forms.ModelForm):
    class Meta:
        model = Normalsender
        fields = ['name', 'email', 'weight', 'phonenumber', 'address', 'description']

class NormalReceiverForm(forms.ModelForm):
    class Meta:
        model = Normalreceiver
        fields = ['name', 'email', 'phonenumber', 'address']

core/views.py
from django.http import BadHeaderError, HttpResponse
from django.shortcuts import redirect, render
from . models import *
from django.core.mail import send_mail
from django.contrib import messages
from django.http import JsonResponse
from django.urls import reverse
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseRedirect
from .forms import *

# Create your views here.

def index(request):
    context = {}
    return render(request, 'index.html', context)


def about(request):
    context = {}
    return render(request, 'about-us.html', context)



def express(request):
    if request.method == 'POST':
        sender_data = {
            'name': request.POST.get('name'),
            'email': request.POST.get('email'),
            'weight': request.POST.get('weight'),
            'phonenumber': request.POST.get('phonenumber'),
            'address': request.POST.get('address'),
            'description': request.POST.get('description')
        }

        receiver_data = {
            'name': request.POST.get('rec_name'),
            'email': request.POST.get('rec_email'),
            'phonenumber': request.POST.get('rec_phonenumber'),
            'address': request.POST.get('rec_address')
        }

        # Debug: Print the form data
        print('Sender Data:', sender_data)
        print('Receiver Data:', receiver_data)

        # Basic validation
        if all(sender_data.values()) and all(receiver_data.values()):
            sender = ExpressSender.objects.create(**sender_data)
            receiver = ExpressReceiver.objects.create(**receiver_data)

            request.session['sender_id'] = sender.id
            request.session['receiver_id'] = receiver.id

            # messages.success(request, 'Data saved successfully.')
            return redirect('payment')
        else:
            messages.error(request, 'Please fill all fields.')

    return render(request, 'express.html')





def normal(request):
    if request.method == 'POST':
        nsender_form = NormalSenderForm(request.POST)
        nreceiver_form = NormalReceiverForm(request.POST)

        if nsender_form.is_valid() and nreceiver_form.is_valid():
            nsender = nsender_form.save()
            nreceiver = nreceiver_form.save()

            request.session['nsender_id'] = nsender.id
            request.session['nreceiver_id'] = nreceiver.id

            return redirect('payments')  
        else:
            messages.error(request, 'Please fill all fields.')
    else:
        nsender_form = NormalSenderForm()
        nreceiver_form = NormalReceiverForm()

    return render(request, 'normal.html', {'nsender_form': nsender_form, 'nreceiver_form': nreceiver_form})




def payment(request):
    wallet = Wallet.objects.first()
    bank = AccountDetail.objects.first()
    sender_id = request.session.get('sender_id')
    receiver_id = request.session.get('receiver_id')

    sender_data = ExpressSender.objects.get(id=sender_id) if sender_id else None
    receiver_data = ExpressReceiver.objects.get(id=receiver_id) if receiver_id else None

    if sender_data:
        weight = float(sender_data.weight)
        cost = weight * 3.50 + 10
        formatted_cost = f"{cost:.2f}"
    else:
        weight = 0
        cost = 0
        formatted_cost = f"{cost:.2f}"

    return render(request, 'payment.html', {
        'sender_data': sender_data,
        'receiver_data': receiver_data,
        'cost': formatted_cost,
        'wallet': wallet,
        'bank': bank,
        # 'formatted_cost':formatted_cost
    })



def payments(request):
    wallet = Wallet.objects.first()
    bank = AccountDetail.objects.first()
    sender_id = request.session.get('nsender_id')
    receiver_id = request.session.get('nreceiver_id')

    sender_data = Normalsender.objects.get(id=sender_id) if sender_id else None
    receiver_data = Normalreceiver.objects.get(id=receiver_id) if receiver_id else None

    if sender_data:
        weight = float(sender_data.weight)
        cost = weight * 3.50
        formatted_cost = f"{cost:.2f}"
    else:
        weight = 0
        cost = 0
        formatted_cost = f"{cost:.2f}"

    return render(request, 'payments.html', {
        'sender_data': sender_data,
        'receiver_data': receiver_data,
        'cost': formatted_cost,
        'wallet': wallet,
        'bank': bank,
    })




def oceanfreight(request):
    context = {}
    return render(request, 'ocean-freight-forwarding.html', context)

def airfreight(request):
    context = {}
    return render(request, 'air-freight-carrier.html', context)

def roadfreight(request):
    context = {}
    return render(request, 'road-freight-forwarding.html', context)

def movements(request):
    context = {}
    return render(request, 'soc-movements.html', context)

def importers(request):
    context = {}
    return render(request, 'importers-logistics-rep.html', context)

def exports(request):
    context = {}
    return render(request, 'export-import.html', context)

def logistics(request):
    context = {}
    return render(request, 'logistics.html', context)

def contact(request):
    if request.method == 'POST':
        # Process form submission
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        phonenumber = request.POST.get('phonenumber')
        message = request.POST.get('message')

        # Save the form data to the database
        contact_form_entry = ContactForm.objects.create(
            name=name,
            email=email,
            subject=subject,
            phonenumber=phonenumber,
            message=message,
        )

        # Prepare and send the notification email to the admin
        sender_name = ' Couriermail'
        sender_email = 'dcmediabusiness1@gmail.com'
        admin_email = 'decarkson@gmail.com'
        admin_subject = 'New Message Received'
        admin_message = (
            f'A new message has been received.\n\n'
            f'Name: {name}\n'
            f'Email: {email}\n'
            f'subject: {subject}\n'
            f'phonenumber: {phonenumber}\n'
            f'Message: {message}'
        )

        try:
            send_mail(
                admin_subject,
                admin_message,
                f'{sender_name} <{sender_email}>',
                [admin_email],
                fail_silently=False,
            )
            messages.success(request, 'Your message has been sent successfully!')
        except BadHeaderError:
            return HttpResponse('Invalid header found.')
        except Exception as e:
            messages.error(request, f'An error occurred: {e}')

        return redirect('index')
    
    context = {}
    return render(request, 'contact-us.html', context)


def household(request):
    context = {}
    return render(request, 'move-household-goods.html', context)

def commercial(request):
    context = {}
    return render(request, 'ship-commercial-goods.html', context)

def international(request):
    context = {}
    return render(request, 'international-freight.html', context)

def domestic(request):
    context = {}
    return render(request, 'domestic-freight.html', context)

def forwarder(request):
    context = {}
    return render(request, 'freight-forwarder.html', context)

def consultation(request):
    context = {}
    return render(request, 'freight-consultation.html', context)

def trackingDetails(request):
    context = {}
    return render(request, 'tracking-details.html', context)


@csrf_exempt
def track_number(request):
    if request.method == 'POST':
        tracking_number = request.POST.get('shipment_tracking_no', '')
        if tracking_number:
            if tracking_number == 'HZEY-JEZIS02-VKALE-ONDESW': 
                redirect_url = request.build_absolute_uri(reverse('trackingDetails'))
                return JsonResponse({'status': 'success', 'redirect_url': redirect_url})
            else:
                return JsonResponse({'status': 'error', 'message': 'Tracking number not found'})
        else:
            return JsonResponse({'status': 'error', 'message': 'Invalid tracking number'})
    return JsonResponse({'status': 'error', 'message': 'Invalid request method'})

core/templates/POST.html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

core/templates/about-us.html
{% extends "base.html" %}
{% load static %}
{% block title %}About Us : Couriermailingworldwide | Express Delivery, Courier &amp; Shipping
Services | Worlwide{% endblock %}

{% block content %}

	<!-- Start of Breadcrumb section
	============================================= -->
	<section id="ft-breadcrumb" class="ft-breadcrumb-section position-relative"
		data-background="{% static "img/bg/bread-bg.jpg" %}">
		<span class="background_overlay"></span>
		<span class="design-shape position-absolute"><img src="{% static "img/shape/tmd-sh.html" %}" alt=""></span>
		<div class="container">
			<div class="ft-breadcrumb-content headline text-center position-relative">
				<h2>About Us</h2>
				<div class="ft-breadcrumb-list ul-li">
					<ul>
						<li><a href="{% url "index" %}">Home</a></li>
						<li>About Us</li>
					</ul>
				</div>
			</div>
		</div>
	</section>
	<!-- End of Breadcrumb section
	============================================= -->




	<!-- Tracking Section -->
	<section class="ft1-tracking-section">
		<div class="auto-container">
			<div class="inner-container">
				<div class="row clearfix">
					<!-- Tracking Column -->
					<div class="tracking-column col-lg-7 col-md-12 col-sm-12">
						<div class="inner-column">
							<!-- Tracking Form -->
							<div class="tracking-form">
								<form method="post" class="search-form" id="frmTrack" name="frmTrack" action="#"
									onsubmit="return false">
									<div class="form-group">
										<input type="search" id="shipment_tracking_no" name="shipment_tracking_no"
											value="" placeholder="Enter Your Tracking Number" required>
										<button class="theme-btn btn-style-two" name="submitTrackNo"
												onclick="trackNowFunc()">Track & Trace <span
												class="icon fas fa-angle-double-right"></span></button>
									</div>
								</form>

								{% comment %} <div id="loadingPop" style="display:none;">Loading...</div> {% endcomment %}
							</div>
						</div>
					</div>



					<!-- Featured Column -->
					<div class="featured-column col-lg-5 col-md-12 col-sm-12">
						<div class="inner-column">
							<div class="row clearfix">

								<!-- Feature Block -->
								<div class="feature-block col-lg-6 col-md-6 col-sm-12">
									<div class="inner-box">
										<div class="icon flaticon-discount"></div>
										<h6>Affordable Premium Shipping!</h6>
									</div>
								</div>

								<!-- Feature Block -->
								<div class="feature-block col-lg-6 col-md-6 col-sm-12">
									<div class="inner-box">
										<div class="icon flaticon-shield-2"></div>
										<h6>Safe & Reliable <br> Courier Services!</h6>
									</div>
								</div>

							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End Tracking Section -->







	<!-- Welcome Section -->
	<section class="ft1-welcome-section">
		<div class="pattern-layer" style="background-image:url({% static "images/background/pattern-1.png" %})"></div>
		<div class="auto-container">
			<div class="inner-container">
				<div class="row clearfix">

					<!-- Image Column -->
					<div class="image-column col-lg-6 col-md-12 col-sm-12">
						<div class="inner-column">
							<div class="image">
								<img src="{% static "images/resource/welcome.jpg" %}" alt="" />
								<div class="year-box">
									<div class="box-inner">
										<span class="icon flaticon-link"></span>
										<strong>10+ Years</strong>
										Of Excellent Services
									</div>
								</div>
							</div>
						</div>
					</div>

					<!-- Content Column -->
					<div class="content-column col-lg-6 col-md-12 col-sm-12">
						<div class="inner-column">
							<div class="sec-title">
								<div class="title">couriermailingworldwides</div>
								<h2 style="font-size:28px;">
									Providing Full Range of Courier And Logistics Services Worldwide
								</h2>



								<div class="text">
									<p>COURIERMAILING Group is one of the world’s leading logistic /Security company.  The Group connects people and markets and is an enabler of global trade. It aspires to be the first choice for customers, employees and investors worldwide.
									</p>





									<p>
										To this end, COURIERMAILING Group is focusing on growth in its profitable core logistics businesses and accelerating the digital transformation in all business divisions.
									</p>




								</div>
							</div>




							<p>
								The Group contributes to the world through sustainable business practices, corporate citizenship and environmental activities. By the year 2050, COURIERMAILING Group aims to achieve net-zero emissions logistics.
							</p>


							<!--
								<div class="button-box">
									<a href="#" class="theme-btn btn-style-three">
									Explore More <span class="icon fas fa-angle-double-right"></span></a>
								</div>
								-->
						</div>
					</div>

				</div>
			</div>
		</div>
	</section>
	<!-- End Welcome Section -->







	<!-- Start of goodness feature section
	============================================= -->
	<section id="ft-goodness-feature" class="ft-goodness-feature-section">
		<div class="container">
			<div class="ft-section-title-2 headline pera-content text-center">
				<h2>Our Services</h2>
				<p>
					Our services include armored car transportation, money processing,
					long-distance transport of valuables, vaulting and other value-added solutions.
				</p>
			</div>
			<div class="ft-goodness-featured-content">
				<div class="row">
					<div class="col-lg-4 col-md-6">
						<div class="ft-goodness-featured-innerbox text-center">
							<div class="ft-goodness-featured-icon d-flex align-items-center justify-content-center">
								<i class="fal fa-anchor"></i>
							</div>
							<div class="ft-goodness-featured-text headline pera-content">
								<h3>Our Mission</h3>
								<p>
									We meet our customers' demands for a personal & profesional
									service by offering innovative supply chain solutions.
								</p>
							</div>
						</div>
					</div>
					<div class="col-lg-4 col-md-6">
						<div class="ft-goodness-featured-innerbox text-center">
							<div class="ft-goodness-featured-icon d-flex align-items-center justify-content-center">
								<i class="fal fa-user-headset"></i>
							</div>
							<div class="ft-goodness-featured-text headline pera-content">
								<h3>Our Vision</h3>
								<p>
									We proactively and constantly look for new possibilities. Therefore,
									an important part of our vision is to attract & retain.
								</p>
							</div>
						</div>
					</div>
					<div class="col-lg-4 col-md-6">
						<div class="ft-goodness-featured-innerbox text-center">
							<div class="ft-goodness-featured-icon d-flex align-items-center justify-content-center">
								<i class="fal fa-badge-sheriff"></i>
							</div>
							<div class="ft-goodness-featured-text headline pera-content">
								<h3>Core Values</h3>
								<p>
									Procedures, values and attitudes are crucial to our reputation – not to mention the
									success we enjoy.
								</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End of goodness feature section
	============================================= -->

	<!-- Start of Footer   section
	============================================= -->
{% endblock %}

core/templates/contact-us.html
{% extends "base.html" %}
{% load static %}
{% block title %}Contact Us : Couriermailingworldwide | Express Delivery, Courier &amp; Shipping Services | Worlwide{% endblock %}

{% block content %}

	<!-- Start of Breadcrumb section
	============================================= -->
	<section id="ft-breadcrumb" class="ft-breadcrumb-section position-relative"
		data-background="{% static "img/bg/bread-bg.jpg" %}">
		<span class="background_overlay"></span>
		<span class="design-shape position-absolute"><img src="{% static "img/shape/tmd-sh.html" %}" alt=""></span>
		<div class="container">
			<div class="ft-breadcrumb-content headline text-center position-relative">
				<h2>Contact Us</h2>
				<div class="ft-breadcrumb-list ul-li">
					<ul>
						<li><a href="{% url "index" %}">Home</a></li>
						<li>Contact Us</li>
					</ul>
				</div>
				 <!--message Alert-->
				 <div class="alert-container">
					{% if messages %}
						{% for message in messages %}
							<div class="alert alert-warning alert-dismissible fade show alert-timeout" role="alert">
								<strong>Hello!</strong> {{ message }}.
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
							</div>
						{% endfor %}
					{% endif %}
				</div>
		
				<script>
					// Function to hide the alert after 9 seconds
					setTimeout(function() {
						var alerts = document.getElementsByClassName('alert-timeout');
						for (var i = 0; i < alerts.length; i++) {
							alerts[i].style.display = 'none';
						}
					}, 9000); 
				</script>
			</div>
		</div>
	</section>
	<!-- End of Breadcrumb section
	============================================= -->










	<!-- Tracking Section -->
	<section class="ft1-tracking-section">
		<div class="auto-container">
			<div class="inner-container">
				<div class="row clearfix">
					<!-- Tracking Column -->
					<div class="tracking-column col-lg-7 col-md-12 col-sm-12">
						<div class="inner-column">
							<!-- Tracking Form -->
							<div class="tracking-form">
								<form method="post" class="search-form" id="frmTrack" name="frmTrack" action="#"
									onsubmit="return false">
									<div class="form-group">
										<input type="search" id="shipment_tracking_no" name="shipment_tracking_no"
											value="" placeholder="Enter Your Tracking Number" required>
										<button class="theme-btn btn-style-two" name="submitTrackNo"
												onclick="trackNowFunc()">Track & Trace <span
												class="icon fas fa-angle-double-right"></span></button>
									</div>
								</form>

								{% comment %} <div id="loadingPop" style="display:none;">Loading...</div> {% endcomment %}
							</div>
						</div>
					</div>





					<!-- Featured Column -->
					<div class="featured-column col-lg-5 col-md-12 col-sm-12">
						<div class="inner-column">
							<div class="row clearfix">

								<!-- Feature Block -->
								<div class="feature-block col-lg-6 col-md-6 col-sm-12">
									<div class="inner-box">
										<div class="icon flaticon-discount"></div>
										<h6>Affordable Premium Shipping!</h6>
									</div>
								</div>

								<!-- Feature Block -->
								<div class="feature-block col-lg-6 col-md-6 col-sm-12">
									<div class="inner-box">
										<div class="icon flaticon-shield-2"></div>
										<h6>Safe & Reliable <br> Courier Services!</h6>
									</div>
								</div>

							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End Tracking Section -->





	<!-- Start of contact page section
	============================================= -->
	<section id="ft-contact-page" class="ft-contact-page-section page-padding">
		<div class="container">
			<div class="ft-contact-page-content">
				<div class="row">
					<div class="col-lg-6">
						<div class="ft-contact-page-text-wrapper">
							<div class="ft-section-title-2 headline pera-content">
								<span class="sub-title">Get a Quote</span>
								<h2>Get in Touch
								</h2>
							</div>
							<div class="ft-contact-page-contact-info">
								<div class="ft-contact-cta-items d-flex">
									<div class="ft-contact-cta-icon d-flex align-items-center justify-content-center">
										<i class="fal fa-map-marker-alt"></i>
									</div>
									<div class="ft-contact-cta-text headline pera-content">
										<h3>Office addresses</h3>
										<p>
											<b>Turkey Address</b><br> <hr>
											2 Istanbul Sisli, Buyukdere Ave
											34158 Istanbul, Buyukdere Ave<br> <br>

											<b>Germany Address</b>  <br> <hr>
											Thurn-und Taxis-Platz 6
											D-60313 Frankfurt<br> <br>
											<b>USA Address</b> <br> <hr>
											952 Heritage Hills Rd
											Decatur, Georgia(GA), 30033
										</p>
									</div>
								</div>
								<div class="ft-contact-cta-items d-flex">
									<div class="ft-contact-cta-icon d-flex align-items-center justify-content-center">
										<i class="fas fa-phone-alt"></i>
									</div>
									<div class="ft-contact-cta-text headline pera-content">
										<h3>Telephone number</h3>
										<p>+1 678 528 9797 <br>
											+905358430689 <br>
											+4915735984842</p>
									</div>
								</div>
								<div class="ft-contact-cta-items d-flex">
									<div class="ft-contact-cta-icon d-flex align-items-center justify-content-center">
										<i class="far fa-envelope"></i>
									</div>
									<div class="ft-contact-cta-text headline pera-content">
										<h3>Mail address</h3>

										<p>couriermail@diplomats.com </p>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-6">
						<div class="ft-contact-page-form-wrapper headline">
							<h3 class="text-center">Send Us A Mail</h3>

							<form action="{% url 'contact' %}" class="form-group" method="post" id="contactForm" name="contactForm">
								{% csrf_token %}
								<div class="row">
									<div class="col-lg-6">
										<input type="text" name="name" id="name" placeholder="Your Name" required value="{{ form.name.value|default_if_none:'' }}">
										{% if form.name.errors %}
                                            <div class="text-danger">{{ form.name.errors }}</div>
                                        {% endif %}
									</div>
									<div class="col-lg-6">
										<input type="email" name="email" id="id_email" pattern="[^ @]*@[^ @]*" class="form-control" placeholder="Email address" required value="{{ form.email.value|default_if_none:'' }}">
                                        {% if form.email.errors %}
                                            <div class="text-danger">{{ form.email.errors }}</div>
                                        {% endif %}
									</div>
									<div class="col-lg-6">
										<input type="text" name="subject" id="subject" placeholder="Subject" required value="{{ form.subject.value|default_if_none:'' }}">
										{% if form.name.errors %}
                                            <div class="text-danger">{{ form.name.errors }}</div>
                                        {% endif %}
									</div>
									<div class="col-lg-6">
										<input type="text" name="phonenumber" id="phonenumber" placeholder="Phone number" required value="{{ form.phonenumber.value|default_if_none:'' }}">
										{% if form.name.errors %}
                                            <div class="text-danger">{{ form.name.errors }}</div>
                                        {% endif %}
									</div>


									<div class="col-lg-12">
										<textarea name="message" rows="6" class="form-control" id="id_message" placeholder="" required>{{ form.message.value|default_if_none:'' }}</textarea>
                                        {% if form.message.errors %}
                                            <div class="text-danger">{{ form.message.errors }}</div>
                                        {% endif %}
									</div>
									<div class="col-lg-12">
										<button type="submit" class="form-control btn btn-primary">Send Message</button>
										{% comment %} <button name="sendMessage" id="sendMessage" type="submit"
											>Send Message</button>
										<button type="reset" name="clear_form" id="clear_form" class="btn btn-primary"
											style="display:none;">Clear Message</button> {% endcomment %}
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End of contact page section
	============================================= -->
{% endblock %}

core/templates/contact_process.html
2